name: Pull requests

on: [pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
    - name: Generate metrics
      uses: tkorakas/pr-metrics@test
